### ISSUE TITLE
Some failing tests on Debian stable (wheezy)

### ISSUE THREAD

**Issue by yarikoptic** [gitpython-developers/GitPython#252]
Finally I have built (with buildtime testing)/uploaded both gitdb and GitPython to Debian and backports to NEuroDebian -- hoorrayy -- thanks.  But while building on Debian wheezy few tests still failing.  I will send you 2 PRs of changes I have done to be able to run

```
    : # run tests only if we can fetch original sources repository
    -mkdir -p build/test; cd build/test; \
         git config --global http.sslVerify false; git config --global user.name "TESTING"; git config --global user.email "TESTING@example.com"; \
         git clone git://github.com/gitpython-developers/GitPython; \
         cd GitPython; git submodule update --init --recursive; \
          for i in `seq 4`; do git reset --hard HEAD~1; done; git reset --hard origin/master; touch ../go
    [ ! -e build/test/go ] || \
     GIT_PYTHON_TEST_GIT_REPO_BASE=$(CURDIR)/build/test/GitPython \
     nosetests -s -v git/test
```

1. This one you reported before also on Centos 6.5 (git 1.7.1, python 2.6.6)
```
======================================================================
ERROR: test_head_reset (git.test.test_refs.TestRefs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/test/lib/helper.py", line 118, in repo_creator
    return func(self, rw_repo)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/test/test_refs.py", line 507, in test_head_reset
    refs = list(SymbolicReference.iter_items(rw_repo))
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/refs/symbolic.py", line 623, in <genexpr>
    return (r for r in cls._iter_items(repo, common_path) if r.__class__ == SymbolicReference or not r.is_detached)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/refs/symbolic.py", line 600, in _iter_items
    yield cls.from_path(repo, path)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/refs/symbolic.py", line 642, in from_path
    if instance.__class__ == SymbolicReference and instance.is_detached:
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/refs/symbolic.py", line 348, in is_detached
    self.ref
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/refs/symbolic.py", line 255, in _get_reference
    sha, target_ref_path = self._get_ref_info(self.repo, self.path)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/refs/symbolic.py", line 159, in _get_ref_info
    if tokens[0] == 'ref:':
IndexError: list index out of range
```
2.
```
======================================================================
ERROR: test_git_submodules (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/test/test_submodule.py", line 686, in test_git_submodules
    sm.move(sm.path + '_moved')
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/util.py", line 57, in wrapper
    return func(self, *args, **kwargs)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/objects/submodule/base.py", line 705, in move
    self._write_git_file_and_module_config(module_checkout_abspath, module_abspath)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/objects/submodule/base.py", line 295, in _write_git_file_and_module_config
    writer = GitConfigParser(os.path.join(module_abspath, 'config'), read_only=False, merge_includes=False)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/config.py", line 209, in __init__
    self._lock._obtain_lock()
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/util.py", line 558, in _obtain_lock
    return self._obtain_lock_or_raise()
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/util.py", line 551, in _obtain_lock_or_raise
    raise IOError(str(e))
IOError: [Errno 2] No such file or directory: '/tmp/test_git_submodulesKYzrbc/parent/module/config.lock'
```

3.

```
======================================================================
FAIL: test_rename (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/tmp/buildd/python-git-0.3.6+git5-gd8bbfea/git/test/test_submodule.py", line 784, in test_rename
    assert sm_mod.git_dir.endswith(join_path_native('.git', 'modules', new_sm_name))
AssertionError
```

**Comment by yarikoptic** [comment]
btw git 1.7.10.4-1  and  python 2.7.3

**Comment by Byron** [comment]
Now that the PRs have been merged, does that mean this issue is fixed as well ? For some reason, I do hope so ;) !

**Comment by Byron** [comment]
You can watch the archived live-development stream [on youtube](http://youtu.be/nsFxzwkvwcQ).

**Comment by yarikoptic** [comment]
My PRs dealt with none of these failures on wheezy, so I guess they still persist.  I will check in a second

**Comment by Byron** [comment]
1. What's your schedule for getting these fixed ? I'd do it until until Sunday otherwise.
1. Is the script you pasted above all I'd need to reproduce these issues ?

**Comment by yarikoptic** [comment]
1. Sunday sounds great ;)  no rush for me really -- my devel box is running jessie/sid, so making it work on stable is not of as high urgency

2. no need to sweat with that one even.... on a wheezy box following one also brings the same errors

```
git clone git://github.com/gitpython-developers/GitPython; cd GitPython; git submodule update --init --recursive; for i in `seq 4`; do git reset --hard HEAD~1; done; git reset --hard origin/master; nosetests -s -v git/test 2>&1 ;
```

**Comment by Byron** [comment]
The archived stream can be found [on youtube](http://youtu.be/07zgWdmPTZg).
